{{- if .Values.clickhouseSecretMonitor.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-secret-monitor
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/name: "clickhouse-secret-monitor"
    app.kubernetes.io/component: "clickhouse-secret-monitor"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clickhouse-secret-monitor
  template:
    metadata:
      labels:
        name: clickhouse-secret-monitor
        app: clickhouse-secret-monitor
    spec:
      {{- if .Values.clickhouseSecretMonitor.affinity }}
      affinity: {{ .Values.clickhouseSecretMonitor.affinity | toJson }}
      {{- else if .Values.affinity }}
      affinity: {{ .Values.affinity | toJson }}    
      {{- end }}
      containers:
        - name: clickhouse-secret-monitor
          image: {{ template "clickhouse_secret_monitor.image" . }}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SECRET_NAMES
              value: 
            {{  include "clickhouse.users" . | indent 4 }}
          resources:
            requests:
              memory: {{ default "256Mi" .Values.clickhouseSecretMonitor.resources.requests.memory }}
              cpu: {{ default "200m" .Values.clickhouseSecretMonitor.resources.requests.cpu }}
            limits:
              memory: {{ default "256Mi" .Values.clickhouseSecretMonitor.resources.limits.memory }}
              cpu: {{ default "400m" .Values.clickhouseSecretMonitor.resources.limits.cpu }}        
          securityContext:
            {{- include "clickhouse.globalContainerSecurityContext" . | nindent 12 }}
            {{- with .Values.clickhouseSecretMonitor.securityContext.container }}
            {{- toYaml . | nindent 12 -}}
            {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ .Values.clickhouseOperator.serviceAccountName }}
      securityContext:
        {{ (include "clickhouse.globalPodSecurityContext" . | nindent 8) }}
        {{- with .Values.clickhouseSecretMonitor.securityContext.pod }}
        {{- toYaml . | nindent 8 -}}
        {{- end }}
{{- end }}




