{{- if .Values.integrationTests.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-integration-tests
  labels:
    app: clickhouse-integration-tests
    name: clickhouse-integration-tests
    {{ include "kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/technology: "python"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-integration-tests
  template:
    metadata:
      labels:
        app: clickhouse-integration-tests
    spec:
      containers:
        - name: clickhouse-integration-tests
          image: {{ template "clickhouseIntegrationTests.image" . }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLICKHOUSE_HOST
              value: {{ .Values.integrationTests.clickhouseHost }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.integrationTests.clickhousePort | quote }}
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-integration-tests-secret
                  key: clickhouse_user
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-integration-tests-secret
                  key: clickhouse_password
            - name: CLICKHOUSE_BACKUP_HOST
              value: {{ .Values.integrationTests.clickhouseBackupHost }}
            - name: CLICKHOUSE_BACKUP_PORT
              value: {{ .Values.integrationTests.clickhouseBackupPort | quote }}
            - name: TAGS
              value: {{ .Values.integrationTests.tags }}
            - name: STATUS_CUSTOM_RESOURCE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TLS_ENABLED
            {{- if .Values.tls.enabled }}
              value: "true"
            {{- else }}
              value: "false"
            {{- end }}
            - name: TIMEOUT_BEFORE_START
              value: {{ .Values.integrationTests.timeoutBeforeStart | default 30 | quote }}
            - name: RANDOM_RUN_TRIGGER
              value: {{ randAlphaNum 10 | quote }}
          resources:
            requests:
              memory: {{ default "256Mi" .Values.integrationTests.resources.requests.memory }}
              cpu: {{ default "200m" .Values.integrationTests.resources.requests.cpu }}
            limits:
              memory: {{ default "256Mi" .Values.integrationTests.resources.limits.memory }}
              cpu: {{ default "400m" .Values.integrationTests.resources.limits.cpu }}
          volumeMounts:
            - name: output
              mountPath: /opt/robot/output
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            {{- include "clickhouse.globalContainerSecurityContext" . | nindent 12 }}
            {{- with .Values.integrationTests.securityContext.container }}
            {{- toYaml . | nindent 12 -}}
            {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: clickhouse-integration-tests
      volumes:
        - name: output
          emptyDir: { }
      securityContext:
        {{- include "clickhouse.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.integrationTests.securityContext.pod }}
        {{- toYaml . | nindent 8 -}}
        {{- end }}
{{- end -}}