{{- if .Values.integrationTests.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-tests-runner
  labels:
    app: clickhouse-tests-runner
    name: clickhouse-tests-runner
    {{ include "kubernetes.labels" . | nindent 4 }}
    app.kubernetes.io/technology: "go"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-tests-runner
  template:
    metadata:
      labels:
        app: clickhouse-tests-runner
    spec:
      {{- if .Values.integrationTests.affinity }}
      affinity: {{ .Values.integrationTests.affinity | toJson }}
      {{- else if .Values.affinity }}
      affinity: {{ .Values.affinity | toJson }}
      {{- end }}
      serviceAccountName: clickhouse-integration-tests
      containers:
        - name: clickhouse-tests-runner
          image: {{ template "clickhouseTestsRunner.image" . }}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHI_NAME
              value: {{ .Values.integrationTests.chiName | default "cluster" | quote }}
            - name: TEST_IMAGE
              value: {{ .Values.integrationTests.image | quote }}
            - name: TAGS
              value: {{ .Values.integrationTests.tags | quote }}
            - name: CLICKHOUSE_HOST
              value: {{ .Values.integrationTests.clickhouseHost | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.integrationTests.clickhousePort | quote }}
            - name: CLICKHOUSE_BACKUP_HOST
              value: {{ .Values.integrationTests.clickhouseBackupHost | quote }}
            - name: CLICKHOUSE_BACKUP_PORT
              value: {{ .Values.integrationTests.clickhouseBackupPort | quote }}
            - name: SERVICE_ACCOUNT_NAME
              value: "clickhouse-integration-tests"
            - name: TLS_ENABLED
            {{- if .Values.tls.enabled }}
              value: "true"
            {{- else }}
              value: "false"
            {{- end }}
          resources:
            requests:
              memory: {{ default "64Mi" .Values.integrationTests.runnerResources.requests.memory }}
              cpu: {{ default "50m" .Values.integrationTests.runnerResources.requests.cpu }}
            limits:
              memory: {{ default "128Mi" .Values.integrationTests.runnerResources.limits.memory }}
              cpu: {{ default "100m" .Values.integrationTests.runnerResources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- include "clickhouse.globalContainerSecurityContext" . | nindent 12 }}
            {{- with .Values.integrationTests.securityContext.container }}
            {{- toYaml . | nindent 12 -}}
            {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- include "clickhouse.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.integrationTests.securityContext.pod }}
        {{- toYaml . | nindent 8 -}}
        {{- end }}
{{- end -}}
