{{- if .Values.integrationTests.install }}
kind: Secret
apiVersion: v1
metadata:
  name: clickhouse-integration-tests-secret
  labels:
    name: clickhouse-integration-tests-secret
    {{ include "kubernetes.labels" . | nindent 4 }}
stringData:
  clickhouse_user: "{{ .Values.integrationTests.credentials.clickhouse.user }}"
  clickhouse_password: "{{ ( include "clickhouse.integrationTests.adminPassword" . ) }}"
{{- end }}
