{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-integration-tests
  labels:
    name: clickhouse-integration-tests
    {{ include "kubernetes.labels" . | nindent 4 }}
{{- end }}
