{{- if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nc-dbaas-clickhouse-adapter
    name: nc-dbaas-user-credentials
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: nc-dbaas-user-credentials
data:
  username: {{ include "clickhouse.dbaas.user" . | b64enc }}
  password: {{ include "clickhouse.dbaas.password" . | b64enc }}
type: Opaque
{{- end }}