{{ if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nc-dbaas-clickhouse-adapter
    name: nc-dbaas-adapter-credentials
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: nc-dbaas-adapter-credentials
data:
  {{- if .Values.dbaas.adapter }}
  username: {{ include "clickhouse.dbaas.adapter.user" . | b64enc }}
  password: {{ include "clickhouse.dbaas.adapter.password" . | b64enc }}
  {{- else }}
  username: {{ "user" | b64enc }}
  password: {{ .Values.dbaas.clickhouse.password | b64enc }}
{{- end }}
type: Opaque
{{ end }}