{{- if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nc-dbaas-clickhouse-adapter
    name: nc-dbaas-aggregator-registration-credentials
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: nc-dbaas-aggregator-registration-credentials
data:
  password: {{ default "Bnmq5567_PO" .Values.dbaas.aggregator.registrationPassword | b64enc }}
  username: {{ default "cluster-dba" .Values.dbaas.aggregator.registrationUsername | b64enc }}
type: Opaque
{{- end }}