{{- if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nc-dbaas-clickhouse-adapter
    name: nc-dbaas-aggregator-registration-credentials
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: nc-dbaas-aggregator-registration-credentials
data:
  password: {{ include "clickhouse.dbaas.aggregator.password" . | b64enc }}
  username: {{ include "clickhouse.dbaas.aggregator.user" . | b64enc }}
type: Opaque
{{- end }}