{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq .Values.PAAS_PLATFORM "KUBERNETES") -}}
{{- if and .Values.clickhouseCluster.install .Values.clickhouseCluster.ingressHttp -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-gateway-clickhouse
  labels:
    name: http-gateway-clickhouse
    {{ include "kubernetes.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "clickhouse.gateway.name" . }}
    group: gateway.networking.k8s.io
    kind: Gateway
    namespace: {{ include "clickhouse.gateway.namespace" . }}
    port: {{ if .Values.tls.enabled }}443{{ else }}80{{ end }}
  hostnames: [{{ .Values.clickhouseCluster.ingressHttp.host | quote }}]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: clickhouse-{{ .Values.clickhouseCluster.name }}
      group: ""
      kind: Service
      port: {{ if .Values.tls.enabled }}8443{{ else }}8123{{ end }}
{{- end }}
{{- end }}
