{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq .Values.PAAS_PLATFORM "KUBERNETES") -}}
{{- if and .Values.clickhouseCluster.install .Values.clickhouseCluster.ingressHttp -}}
apiVersion: {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}"networking.k8s.io/v1"{{ else }}"networking.k8s.io/v1beta1"{{ end }}
kind: Ingress
metadata:
  {{- if or .Values.clickhouseCluster.ingressHttp.annotations .Values.tls.enabled }}
  annotations:
    {{- if .Values.clickhouseCluster.ingressHttp.annotations }}
    {{- .Values.clickhouseCluster.ingressHttp.annotations | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'on'
    nginx.ingress.kubernetes.io/proxy-ssl-name: '{{ printf "clickhouse-cluster.%s" .Release.Namespace }}'
    nginx.ingress.kubernetes.io/proxy-ssl-secret: '{{ printf "%s/%s" .Release.Namespace .Values.tls.certificateSecretName }}'
    {{- end }}
  {{- end }}
  labels:
    name: http-route-clickhouse
    {{ include "kubernetes.labels" . | nindent 4 }}
{{- if .Values.clickhouseCluster.ingressHttp.labels }}
{{ .Values.clickhouseCluster.ingressHttp.labels | toYaml | nindent 4 }}
{{- end }}
  name: http-route-clickhouse
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.clickhouseCluster.ingressHttp.host }}
  {{- end }}
  rules:
  - host: {{ .Values.clickhouseCluster.ingressHttp.host }}
    http:
      paths:
        - path: /
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: clickhouse-{{ .Values.clickhouseCluster.name }}
              port:
                {{- if .Values.tls.enabled }}
                number: 8443
                {{- else }}
                number: 8123
                {{- end }}
          {{- else }}
          backend:
            serviceName: clickhouse-{{ .Values.clickhouseCluster.name }}
            servicePort: "http"
          {{- end }}
{{- end }}
{{- end }}
