global:
  cloudIntegrationEnabled: false

clickhouseOperator:
  name: clickhouse-operator
  install: true
  role:
    install: true
  events: true
  credentialsToInstances:
    chCredentialsSecretName: clickhouse-credentials

clickhouseCluster:
  install: true
  name: cluster
  zookeeperHost: zookeeper.zookeeper-service.svc
  replicasCount: 1
  storageClassName: local-path
  storage: 10Gi

  ## Uncomment to test OpenShift Route (no TLS):
  # routeHttp:
  #   host: clickhouse-rest.test.org

  ## Uncomment to test Kubernetes Ingress:
  # ingressHttp:
  #   host: clickhouse-rest.test.org

  ## Uncomment to test Gateway API HTTPRoute (no TLS):
  httpRoute:
    host: mich0724-click.paas-miniha-kubernetes.openshift.sdntest.netcracker.com
    gatewayName: default-external-gateway
    gatewayNamespace: gateway-system

tls:
  enabled: false
  certificateSecretName: ch-cert

clickhouseHook:
  install: false

postHook:
  install: false

backupDaemon:
  install: false
  storage:
    remote: ""

disasterRecovery: null

securityContext: {}
