{
 "title": "ClickHouse Metrics Dashboard",
 "description": "Alitinity Clickhouse Operator metrics exported by Monitoring Agent",
 "tags": [
  "clickhouse",
  "operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\"}, cluster)"
    }
   },
   {
    "name": "exported_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\", cluster=~\"$cluster\"}, exported_namespace)"
    }
   },
   {
    "name": "chi",
    "label": "K8S Clickhouse Installation",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\", exported_namespace=~\"$exported_namespace\", cluster=~\"$cluster\"}, chi)"
    }
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\",exported_namespace=~\"$exported_namespace\",chi=~\"$chi\", cluster=~\"$cluster\"}, hostname)"
    }
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active instances",
   "type": "stat",
   "description": "Number of active clickhouse instances",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)/min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod))"
    }
   ]
  },
  {
   "title": "ClickHouse instances status",
   "type": "state-timeline",
   "description": "ClickHouse instances status (1=UP, 0=DOWN)",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)/min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU/RAM Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container)(\nrate(container_cpu_usage_seconds_total{image!=\"\",io_kubernetes_container_name!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}[1m]))) by (container, pod)",
     "legendFormat": "Usage: {{ pod  }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Requests: {{ exported_pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Limits: {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container)(\nrate(container_cpu_usage_seconds_total{image!=\"\",io_kubernetes_container_name!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}[1m]))) by (container, pod)",
     "legendFormat": "Usage: {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Requests: {{ exported_pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Limits: {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container)(\nrate(container_cpu_usage_seconds_total{image!=\"\",io_kubernetes_container_name!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}[1m]))) by (container, pod)",
     "legendFormat": "Usage: {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Requests: {{ exported_pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", exported_namespace=\"$namespace\", cluster=~\"$cluster\"}) by (container, exported_pod)",
     "legendFormat": "Limits: {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-0-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-1-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage per container in pod against resource requests and limits",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"POD\", pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", namespace=\"$exported_namespace\",container=\"clickhouse-pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_pod=~\"chi-cluster-replicated-[0-9]-2-[0-9]+\", exported_namespace=\"$exported_namespace\", cluster=~\"$cluster\"}) by (exported_pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "ClickHouse cluster metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_Uptime{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Clickhouse operator metrics-exporter fails when grab metrics from clickhouse-server\n\nPlease look pods status\n\nkubectl get pods --all-namespaces | grep clickhouse",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chi_clickhouse_metric_fetch_errors{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\",fetch_type=\"system.metrics\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "description": "For example, version 11.22.33 is translated to 11022033",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_VersionInteger{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ReadOnly replicas",
   "type": "stat",
   "description": "Check Zookeeper connection, Disk Free space and network interconnection between replicas ASAP",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chi_clickhouse_metric_ReadonlyReplica{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "DNS and Distributed Connection Errors",
   "type": "timeseries",
   "description": "Show DNS errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_NetworkErrors{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "NetworkErrors {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailAtAll{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "DistributedConnectionFailAtAll {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailTry{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "DistributedConnectionFailTry {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DNSError{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "DNSErrors {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication and ZooKeeper Exceptions",
   "type": "timeseries",
   "description": "Show readonly and partial shutdown replicas, zookeeer exceptions, zookeeer sessions, zookeeper init requests",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReadonlyReplica{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "ReadonlyReplica {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ReplicaPartialShutdown{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "ReplicaPartialShutdown {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperInit{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "ZooKeeperInit {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_metric_ZooKeeperSession{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "ZooKeeperSession  {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperHardwareExceptions{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "ZooKeeperHardwareExceptions  {{hostname}}"
    }
   ]
  },
  {
   "title": "Zookeeper Transactions",
   "type": "timeseries",
   "description": "Number of requests to ZooKeeper transactions per seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_ZooKeeperTransactions{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "transactions {{ hostname }}"
    }
   ]
  },
  {
   "title": "Replication Queue Jobs",
   "type": "timeseries",
   "description": "Show how intensive data exchange between replicas in parts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedDataLoss{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "data loss {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartChecks{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "check {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartChecksFailed{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "check fail {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFetches{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "fetch {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFailedFetches{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "fetch fail {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFetchesOfMerged{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "fetch merged {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartMerges{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "replicated merge {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxQueueSize{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "max queue size {{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_TCPConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "tcp {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_HTTPConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "http {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_InterserverConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "interserver {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MySQLConnection{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "mysql {{hostname}}"
    }
   ]
  },
  {
   "title": "Active Parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (chi_clickhouse_table_parts{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\",active=\"1\", cluster=~\"$cluster\"})",
     "legendFormat": "Parts {{hostname}}"
    }
   ]
  },
  {
   "title": "Background Tasks",
   "type": "timeseries",
   "description": "BackgroundPoolTask\t\n---\nNumber of active tasks in BackgroundProcessingPool (merges, mutations, fetches, or replication queue bookkeeping)\n\n\nBackgroundMovePoolTask\n---\nNumber of active tasks in BackgroundProcessingPool for moves\n\n\nBackgroundSchedulePoolTask\t\n---\nA number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_BackgroundPoolTask{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "merge, mutate, fetch {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundSchedulePoolTask{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "clean, alter, replica re-init {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundMovePoolTask{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "moves {{hostname}}"
    }
   ]
  },
  {
   "title": "Max Replica Delay",
   "type": "timeseries",
   "description": "Show seconds when replicated servers can be delayed relative to current time,  when you insert directly in *ReplicatedMegreTree table on one server clickhouse need time to replicate new parts of data to another servers in same shard in background",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxAbsoluteDelay{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "absolute {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxRelativeDelay{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "relative {{hostname}}"
    }
   ]
  },
  {
   "title": "Query Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Select Queries",
   "type": "timeseries",
   "description": "Number of SELECT queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_SelectQuery{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "select {{hostname}}"
    }
   ]
  },
  {
   "title": "Insert Queries",
   "type": "timeseries",
   "description": "Number of INSERT queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertQuery{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Insert queries {{hostname}}"
    }
   ]
  },
  {
   "title": "Delayed/Rejected Inserts",
   "type": "timeseries",
   "description": "delayed query\nNumber of INSERT queries that are throttled due to high number of active data parts for partition in a *MergeTree table.\n\ndelayed blocks\nNumber of times the INSERT of a block to a *MergeTree table was throttled due to high number of active data parts for partition. \n\nrejected blocks\nNumber of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition.\n\n\nplease look\nparts_to_delay_insert\nparts_to_throw_insert\n\nin system.merge_tree_settings table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DelayedInserts{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "delayed  queries {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DelayedInserts{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "delayed blocks {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RejectedInserts{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "rejected blocks {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_DistributedFilesToInsert{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "delayed distributed files {{ hostname }}"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "timeseries",
   "description": "Number of active mutations (ALTER DELETE/ALTER UPDATE) and parts to mutate",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (chi_clickhouse_table_mutations{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"})",
     "legendFormat": "mutations {{hostname}}"
    },
    {
     "expr": "sum by (hostname) (chi_clickhouse_table_mutations_parts_to_do{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"})",
     "legendFormat": "parts_to_do {{hostname}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory for Queries",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated in currently executing queries. \n\nNote that some memory allocations may not be accounted.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryTracking{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "description": "Show how much bytes read and decompress via compressed buffer on each server in cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_CompressedReadBufferBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "uncompressed {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReadCompressedBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "compressed {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReadBufferFromFileDescriptorReadBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "file descriptor {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSReadBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "os {{hostname}}"
    }
   ]
  },
  {
   "title": "Rows Inserted",
   "type": "timeseries",
   "description": "## Tracks rows of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertedRows{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Insert rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_Merge{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "merges {{hostname}}"
    }
   ]
  },
  {
   "title": "Bytes Inserted",
   "type": "timeseries",
   "description": "## Tracks amount of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertedBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Insert bytes {{hostname}}"
    }
   ]
  },
  {
   "title": "Merged Uncompressed Bytes",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MergedUncompressedBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "bytes {{hostname}}"
    }
   ]
  },
  {
   "title": " clickhouse-server Process Memory",
   "type": "timeseries",
   "description": "Memory size allocated for clickhouse-server process\nAvailable for ClickHouse 20.4+\n\nVIRT \nThe total amount of virtual memory used by the task. It includes all code, data and shared libraries plus pages that have been swapped out.\n\nVIRT = SWAP + RES\n\n\nSWAP -- Swapped size (kb)\nThe swapped out portion of a task's total virtual memory image.\n\nRES -- Resident size (kb)\nThe non-swapped physical memory a task has used.\nRES = CODE + USED DATA.\n\nCODE -- Code size (kb)\nThe amount of physical memory devoted to executable code, also known as the 'text resident set' size or TRS\n\nDATA -- Data+Stack size (kb)\nThe amount of physical memory allocated to other than executable code, also known as the 'data resident set' size or DRS.\n\nSHR -- Shared Mem size (kb)\nThe amount of shared memory used by a task. It simply reflects memory that could be potentially shared with other processes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryCode{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "CODE {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryResident{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "RES {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryShared{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "SHR {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryDataAndStack{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "DATA {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryVirtual{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "VIRT {{ hostname }}"
    }
   ]
  },
  {
   "title": "Merged Rows",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MergedRows{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Dictionary Memory",
   "type": "timeseries",
   "description": "Memory size allocated for dictionaries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryDictionaryBytesAllocated{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Primary Keys Memory",
   "type": "timeseries",
   "description": "Memory size allocated for primary keys",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryPrimaryKeyBytesAllocated{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Cluster Disk and CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "timeseries",
   "description": "shows how much space available in the kubernetes pod\n\nbe careful with multiple volumes configuration, kubernetes volume claims and S3 as storage backend",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskFreeBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"} / chi_clickhouse_metric_DiskTotalBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ disk }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Clickhouse Data size on Disk",
   "type": "timeseries",
   "description": "Total disk space used by all parts is the sum of bytes on disk from the system.parts table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskDataBytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Max Part count for Partition",
   "type": "timeseries",
   "description": "Each logical partition defined over `PARTITION BY` contains few physical data \"parts\" ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MaxPartCountForPartition{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Clickhouse Data size on Disk by Database",
   "type": "timeseries",
   "description": "Total data size for all ClickHouse *MergeTree tables\n\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (database) (chi_clickhouse_table_parts_bytes{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"})\n",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "CPU Time per second",
   "type": "timeseries",
   "description": "The time which CPU spent on various types of activity ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_RealTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Real Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_UserTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "User Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_SystemTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "System Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSIOWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS IO Wait {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSCPUWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS CPU Wait {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSCPUVirtualTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS CPU Virtual {{hostname}}"
    }
   ]
  },
  {
   "title": "Marks Cache Hit Rate",
   "type": "timeseries",
   "description": "Show which percent of mark files (.mrk) read from memory instead of disk",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MarkCacheHits{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[2m]) / (irate(chi_clickhouse_event_MarkCacheHits{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[2m]) + irate(chi_clickhouse_event_MarkCacheMisses{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[2m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Detached parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname,reason) (chi_clickhouse_metric_DetachedParts{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"})",
     "legendFormat": "{{reason}} {{hostname}} "
    }
   ]
  },
  {
   "title": "Monitoring Agent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(go_memstats_alloc_bytes_total{container=\"metrics-exporter\" ,namespace=~\"$exported_namespace\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ namespace }} GO malloc bytes / sec"
    },
    {
     "expr": "process_resident_memory_bytes{container=\"metrics-exporter\",namespace=~\"$exported_namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ namespace }} RSS Memory"
    }
   ]
  },
  {
   "title": "CPU Time total",
   "type": "piechart",
   "description": "The time which CPU spent on various types of activity total for the selected period",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_DiskReadElapsedMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Disk Read syscall {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DiskWriteElapsedMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Disk Write syscall {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_NetworkReceiveElapsedMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Network Receive {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_NetworkSendElapsedMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Network Send {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RealTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Real Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_UserTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "User Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_SystemTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "System Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSIOWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS IO Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS CPU Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUVirtualTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "OS CPU Virtual {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ThrottlerSleepMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Throttler Sleep {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DelayedInsertsMilliseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m]) * 1000",
     "legendFormat": "Delayed Insert {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperWaitMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Zookeeper Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_CompileExpressionsMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Compile Expressions {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_MergesTimeMilliseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m]) * 1000",
     "legendFormat": "Merges {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockReadersWaitMilliseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m]) * 1000",
     "legendFormat": "RWLock Reader Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockWritersWaitMilliseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m]) * 1000",
     "legendFormat": "RWLock Writer Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_SelectQueryTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Select Query {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_InsertQueryTimeMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "Insert Query {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3ReadMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "S3 Read {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3WriteMicroseconds{exported_namespace=~\"$exported_namespace\",chi=~\"$chi\",hostname=~\"$hostname\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "S3 Write {{hostname}}"
    }
   ]
  },
  {
   "title": "CH Backup Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "description": "Shows CH Backup Orchestrator Status",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}) by (pod)/min(container_start_time_seconds{namespace=~\"$exported_namespace\", container!=\"POD\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}) by (pod))",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage per container in pod against resource requests and limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container)(rate(container_cpu_usage_seconds_total{namespace=~\"$exported_namespace\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}[$inter]))) by (container, pod)",
     "legendFormat": "Usage: {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=~\"$exported_namespace\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}) by (container, exported_pod)\n",
     "legendFormat": "Requests: {{ exported_pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=~\"$exported_namespace\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}) by (container, exported_pod)\n",
     "legendFormat": "Limits: {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage per container in pod against resource requests and limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$exported_namespace\", container=~\"clickhouse-backup-orchestrator\", image!=\"\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{exported_namespace=~\"$exported_namespace\", container=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}) by (exported_pod)\n",
     "legendFormat": "Requests: {{ exported_pod }}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=~\"cassandra-backup-daemon\", cluster=~\"$cluster\"}) by (exported_pod)\n",
     "legendFormat": "Limits: {{exported_pod}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "description": "Shows Last Backup status",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(backup_storage_last_failed{namespace=~\"$exported_namespace\", job=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"})",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Last Backup Size",
   "type": "timeseries",
   "description": "Size of last successful backup ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "backup_storage_last_successful_size{namespace=~\"$exported_namespace\",job=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}",
     "legendFormat": "ID: {{id}}"
    }
   ]
  },
  {
   "title": "Dumps count",
   "type": "timeseries",
   "description": "Current number of dumps",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "backup_storage_dump_count{namespace=~\"$exported_namespace\",job=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Storage Space Usage",
   "type": "timeseries",
   "description": "Shows used by backups space against total space",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "backup_storage_size{namespace=~\"$exported_namespace\",job=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "backup_storage_space_total{namespace=~\"$exported_namespace\",job=~\"clickhouse-backup-orchestrator\", cluster=~\"$cluster\"}\n",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}