{
 "title": "ClickHouse Performance Dashboard",
 "description": "Helps to visualize most frequent, slowest, failed queries.\r\nShows queries rate per second, table with last queries",
 "tags": [
  "clickhouse",
  "queries",
  "performance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "ClickHouse installation",
    "query": "vertamedia-clickhouse-datasource"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "exported_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\"}, exported_namespace)"
    }
   },
   {
    "name": "chi",
    "label": "Clickhouse Installation",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\", exported_namespace=\"$exported_namespace\"}, chi)"
    }
   },
   { "name": "interval", "query": "5m" },
   { "name": "type", "label": "type", "query": "1,2,3,4" },
   { "name": "top", "label": "top elements", "query": "5,10,15,20,25,30" },
   {
    "name": "user",
    "label": "initial user",
    "query": "SELECT DISTINCT initial_user FROM cluster('all-sharded',system.query_log) WHERE event_date >= today()-3 AND event_time > toDateTime(today()-3) SETTINGS skip_unavailable_shards=1"
   },
   { "name": "query_type", "label": "query type", "query": "all,select,insert" },
   {
    "name": "databases",
    "query": {
     "query": "label_values(chi_clickhouse_table_parts{namespace=\"$exported_namespace\"}, database)"
    }
   },
   {
    "name": "clickhouse_host",
    "label": "ClickHouse Host",
    "query": {
     "query": "label_values(chi_clickhouse_table_parts{namespace=\"$exported_namespace\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top $top request's rate by type: $type; user: $user; query type: $query_type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT * FROM ($rateColumns(\n    substring(query,  1,  45) AS query,\n    count() c)\nFROM cluster('all-sharded',$table)\nWHERE\n    cityHash64(query) global in (\n    SELECT cityHash64(substring(query,  1,  45)) AS h\n    FROM cluster('all-sharded',$table)\n    WHERE\n        $timeFilter\n        AND type in ($type)\n        AND initial_user in ($user)\n        AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\n    GROUP BY h\n    ORDER BY count() desc\n    LIMIT $top)\n    AND type in ($type)\n    AND initial_user in ($user)\n    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))) SETTINGS skip_unavailable_shards=1",
     "query": "SELECT\r\n    t,\r\n    arrayMap((a, diff) -> (a.1, if(diff = 0, 0, a.2 / diff)), groupArr, arrayDifference(arrayMap(x -> t / 1000, groupArr)))\r\nFROM (\r\n    SELECT t, groupArray((query, c)) AS groupArr\r\n    FROM (\r\n        SELECT\r\n            (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t,\r\n            substring(query, 1, 45) AS query,\r\n            count() c\r\n        FROM cluster('all-sharded',$table)\r\n        WHERE $timeFilter\r\n        AND cityHash64(query) GLOBAL IN (\r\n            SELECT cityHash64(substring(query, 1, 45)) AS h\r\n            FROM cluster('all-sharded',$table)\r\n            WHERE $timeFilter\r\n                AND type IN ($type)\r\n                AND initial_user IN ($user)\r\n                AND ('$query_type' = 'all' OR (positionCaseInsensitive(query, '$query_type') = 1))\r\n            GROUP BY h\r\n            ORDER BY count() DESC\r\n            LIMIT $top\r\n            SETTINGS skip_unavailable_shards=1\r\n        )\r\n            AND type IN ($type)\r\n            AND initial_user IN ($user)\r\n            AND ('$query_type' = 'all' OR (positionCaseInsensitive(query, '$query_type') = 1))\r\n        GROUP BY t, query\r\n        ORDER BY t\r\n    )\r\n    GROUP BY t\r\n    ORDER BY t\r\n) SETTINGS skip_unavailable_shards=1",
     "rawQuery": "SELECT\r\n    t,\r\n    arrayMap((a, diff) -> (a.1, if(diff = 0, 0, a.2 / diff)), groupArr, arrayDifference(arrayMap(x -> t / 1000, groupArr)))\r\nFROM (\r\n    SELECT t, groupArray((query, c)) AS groupArr\r\n    FROM (\r\n        SELECT\r\n            (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t,\r\n            substring(query, 1, 45) AS query,\r\n            count() c\r\n        FROM cluster('all-sharded',system.query_log)\r\n        WHERE event_date >= toDate(1663262710) AND event_date <= toDate(1663266310) AND event_time >= toDateTime(1663262710) AND event_time <= toDateTime(1663266310)\r\n        AND cityHash64(query) GLOBAL IN (\r\n            SELECT cityHash64(substring(query, 1, 45)) AS h\r\n            FROM cluster('all-sharded',system.query_log)\r\n            WHERE event_date >= toDate(1663262710) AND event_date <= toDate(1663266310) AND event_time >= toDateTime(1663262710) AND event_time <= toDateTime(1663266310)\r\n                AND type IN (2)\r\n                AND initial_user IN ('','default','clickhouse')\r\n                AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1))\r\n            GROUP BY h\r\n            ORDER BY count() DESC\r\n            LIMIT 5\r\n            SETTINGS skip_unavailable_shards=1\r\n        )\r\n            AND type IN (2)\r\n            AND initial_user IN ('','default','clickhouse')\r\n            AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1))\r\n        GROUP BY t, query\r\n        ORDER BY t\r\n    )\r\n    GROUP BY t\r\n    ORDER BY t\r\n) SETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Types",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "1 - successful start of query execution\n\n2 - successful end of query execution\n\n3 - exception before start of query execution\n\n4 - exception while query execution"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top slow queries by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    avg(query_duration_ms) duration,\n    count() count\nFROM cluster('all-sharded',$table)\nWHERE\n    $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY duration desc\nLIMIT $top",
     "rawQuery": "SELECT t, arrayMap((a, diff) -> (a.1, if(diff = 0, 0, a.2 / diff)), groupArr, arrayDifference(arrayMap(x -> x / 1000, tArr))) FROM ( SELECT t, groupArray((query, c)) AS groupArr, groupArray(t) AS tArr FROM ( SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, substring(query, 1, 45) AS query, count() c FROM cluster('all-sharded',system.query_log) WHERE event_date >= toDate(1586234275) AND event_time >= toDateTime(1586234275) AND cityHash64(query) GLOBAL IN ( SELECT cityHash64(substring(query, 1, 45)) AS h FROM cluster('all-sharded',system.query_log) WHERE event_date >= toDate(1586234275) AND event_time >= toDateTime(1586234275) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY h ORDER BY count() DESC LIMIT 5 SETTINGS skip_unavailable_shards=1 ) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY t, query ORDER BY t ) GROUP BY t ORDER BY t ) SETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top memory consumers by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(memory_usage) usage,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> usage <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    avg(memory_usage) usage,\n    count() count\nFROM cluster('all-sharded',$table)\nWHERE\n    $timeFilter\n    AND type IN ($type)\n    AND initial_user IN ($user)\n    AND ('$query_type' = 'all' OR (positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY query\nORDER BY usage DESC\nLIMIT $top",
     "rawQuery": "SELECT t, arrayMap((a, diff) -> (a.1, if(diff = 0, 0, a.2 / diff)), groupArr, arrayDifference(arrayMap(x -> x / 1000, tArr))) FROM ( SELECT t, groupArray((query, c)) AS groupArr, groupArray(t) AS tArr FROM ( SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, substring(query, 1, 45) AS query, count() c FROM cluster('all-sharded',system.query_log) WHERE event_date >= toDate(1586234300) AND event_time >= toDateTime(1586234300) AND cityHash64(query) GLOBAL IN ( SELECT cityHash64(substring(query, 1, 45)) AS h FROM cluster('all-sharded',system.query_log) WHERE event_date >= toDate(1586234300) AND event_time >= toDateTime(1586234300) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY h ORDER BY count() DESC LIMIT 5 SETTINGS skip_unavailable_shards=1 ) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY t, query ORDER BY t ) GROUP BY t ORDER BY t ) SETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Top failed queries by user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"darkorange\">type</font>,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"cornflowerblue\">3</font>,<font color=\"cornflowerblue\">4</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font><br />    query,<br />    <font color=\"darkorange\">type</font><br /><font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "SELECT\n    rand() as t,\n    substring(query,  1,  70) AS query,\n    type,\n    count() count\nFROM cluster('all-sharded',$table)\nWHERE\n    $timeFilter\n    AND type IN (3,4)\n    AND initial_user IN ($user)\n    AND ('$query_type' = 'all' OR (positionCaseInsensitive(query,  '$query_type') = 1))\nGROUP BY\n    query,\n    type\nORDER BY count desc\nLIMIT $top",
     "rawQuery": "SELECT t, arrayMap((a, diff) -> (a.1, if(diff = 0, 0, a.2 / diff)), groupArr, arrayDifference(arrayMap(x -> x / 1000, tArray))) AS result FROM (SELECT t, groupArray((query, c)) AS groupArr, groupArray(t) AS tArray FROM (SELECT (intDiv(toUInt32(event_time), 2) * 2) * 1000 AS t, substring(query, 1, 45) AS query, count() AS c FROM cluster('all-sharded', system.query_log) WHERE event_date >= toDate(1586234335) AND event_time >= toDateTime(1586234335) AND cityHash64(query) GLOBAL IN (SELECT cityHash64(substring(query, 1, 45)) AS h FROM cluster('all-sharded', system.query_log) WHERE event_date >= toDate(1586234335) AND event_time >= toDateTime(1586234335) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY h ORDER BY count() DESC LIMIT 5 SETTINGS skip_unavailable_shards=1) AND type IN (1,2,3,4) AND initial_user IN ('default') AND ('all' = 'all' OR (positionCaseInsensitive(query, 'all') = 1)) GROUP BY t, query ORDER BY t) GROUP BY t ORDER BY t) SETTINGS skip_unavailable_shards=1",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Request charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reqs/s by type: $type; user: $user; query type: $query_type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">AS</font> t, <font color=\"navajowhite\">count()</font> / <font color=\"cornflowerblue\">120</font> <font color=\"darkorange\">AS</font> cRate <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">IN</font> (<font color=\"darkcyan\">$type</font>) <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">IN</font> (<font color=\"darkcyan\">$user</font>) <font color=\"yellow\">AND</font> (<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">OR</font> positionCaseInsensitive(query, <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>) <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n  $timeSeries AS t,\n count() / 120 AS cRate\nFROM cluster('all-sharded', $table)\nWHERE\n    $timeFilter\n    AND type IN ($type)\n    AND initial_user IN ($user)\n    AND (\n        '$query_type' = 'all'\n        OR positionCaseInsensitive(query, '$query_type') = 1\n    )\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(event_time), 10) * 10) * 1000 AS t, count() / 120 AS cRate FROM cluster('all-sharded', system.query_log) WHERE    event_date >= toDate(1586192459)    AND event_time >= toDateTime(1586192459)    AND type IN (1,2,3,4)    AND initial_user IN ('default')   AND (       '$query_type' = 'all'       OR positionCaseInsensitive(query, 'all') = 1 ) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query duration by type: $type; user: $user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms)  select_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br />    <font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'select'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    quantile(0.5)(query_duration_ms)  select_quantile_50,\n    quantile(0.9)(query_duration_ms)  select_quantile_90\nFROM cluster('all-sharded',$table)\nWHERE\n    $timeFilter\n    AND type = 2\n    AND positionCaseInsensitive(query,  'select') = 1\n    AND initial_user IN ($user)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 10) * 10) * 1000 as t,     quantile(0.5)(query_duration_ms)  select_quantile_50,     quantile(0.9)(query_duration_ms)  select_quantile_90 FROM cluster('all-sharded',system.query_log) WHERE     event_date >= toDate(1595573984) AND event_time >= toDateTime(1595573984)     AND type = 2     AND positionCaseInsensitive(query,  'select') = 1     AND initial_user IN ('default') GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "query_log"
    },
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT\n    $timeSeries as t,\n    quantile(0.5)(query_duration_ms) insert_quantile_50,\n    quantile(0.9)(query_duration_ms) insert_quantile_90\nFROM cluster('all-sharded',$table)\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user in ($user)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 10) * 10) * 1000 as t,     quantile(0.5)(query_duration_ms) insert_quantile_50,     quantile(0.9)(query_duration_ms) insert_quantile_90 FROM cluster('all-sharded',system.query_log) WHERE     event_date >= toDate(1595573984) AND event_time >= toDateTime(1595573984)     AND type = 2 and positionCaseInsensitive(query,  'insert into') = 1     and initial_user in ('default') GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Query log table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query log by type: $type; user: $user; query type: $query_type",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">cluster('all-sharded',$table)</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
     "query": "SELECT\n    event_time,\n    hostName() host,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    concat(substring(query,1,120), '...') query\nFROM cluster('all-sharded',$table)\nWHERE $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' OR (positionCaseInsensitive(query,  '$query_type') = 1))\nORDER BY event_time DESC\nLIMIT 1000",
     "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 10) * 10) * 1000 as t,     avg(query_duration_ms)  select_duration FROM cluster('all-sharded',system.query_log) WHERE     event_date >= toDate(1586232299) AND event_time >= toDateTime(1586232299)     AND type = 2     and positionCaseInsensitive(query,  'select') = 1     and initial_user in ('default') GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Databases and Tables statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of parts by  tables for \"$databases\" database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes count of parts for tables in databases.\nPanel is scalable by database and can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
     "repeat": "databases",
     "targets": [
      {
       "expr": "chi_clickhouse_table_parts{active!=\"0\", database=~\"$databases\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"}",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Count of rows in parts by tables for \"$databases\" database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes count of rows in parts by tables in databases.\nPanel is scalable by database and can be filtered by clickhouse host\n",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 46 },
     "repeat": "databases",
     "targets": [
      {
       "expr": "chi_clickhouse_table_parts_rows{active!=\"0\", database=~\"$databases\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"}",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Size of  tables for \"$databases\" database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes Size of  tables for database in MBytes on clickhouse host.\n\tPanel is scalable by database and can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 57 },
     "repeat": "databases",
     "targets": [
      {
       "expr": "chi_clickhouse_table_parts_bytes{active!=\"0\", database=~\"$databases\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"} / 1000000",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Uncompressed size of  tables for \"$databases\" database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes uncompressed size of  tables for database in MBytes on clickhouse host.\n\tPanel is scalable by database and can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 68 },
     "repeat": "databases",
     "targets": [
      {
       "expr": "chi_clickhouse_table_parts_bytes_uncompressed{active!=\"0\", database=~\"$databases\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"} / 1000000",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Count of parts per database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes count of parts per database.\n\tPanel can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum by(database) (chi_clickhouse_table_parts{active!=\"0\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Size of all tables per database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes size of all tables per database in MBytes.\n\tPanel can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "sum by(database) (chi_clickhouse_table_parts_bytes{active!=\"0\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"}) / 100000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count of parts for all tables per database on $clickhouse_host",
     "type": "timeseries",
     "description": "This panel describes count of parts for all tables per database.\n\tPanel can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by(database) (chi_clickhouse_table_parts_rows{active!=\"0\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"}) / 100000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uncompressed size of all tables by  database on $clickhouse_host",
     "type": "timeseries",
     "description": "Uncompressed size of all tables perdatabase on $clickhouse_host\n\tThis panel describes uncompressed size of all tables perdatabase in MBytes.\n\tPanel can be filtered by clickhouse host",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum by(database) (chi_clickhouse_table_parts_bytes_uncompressed{active!=\"0\", hostname=~\"$clickhouse_host\", exported_namespace=\"$exported_namespace\"}) / 100000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}