{{- if and (eq (include "clickhouse.certificatesSpecified" .) "true") (and (not .Values.tls.generateCerts.enabled) .Values.tls.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.certServicesSecret" . }}
  labels:
    name: {{ include "clickhouse.certServicesSecret" . }}
    {{ include "kubernetes.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.tls.certificates.tls_crt }}
  tls.crt: {{ .Values.tls.certificates.tls_crt | quote }}
  {{ end }}
  {{- if .Values.tls.certificates.tls_key }}
  tls.key: {{ .Values.tls.certificates.tls_key | quote }}
  {{ end }}
  {{- if .Values.tls.certificates.ca_crt }}
  ca.crt: {{ .Values.tls.certificates.ca_crt | quote }}
  {{ end }}
type: Opaque
{{- end }}