{{- if .Values.postHook.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-hook-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade  
    "helm.sh/hook-weight": "0"  
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed  
  labels:
    name: {{ .Values.clickhouseOperator.name }}
    {{ include "kubernetes.labels" . | nindent 4 }}
{{- end }}
