{{- if .Values.clickhouseHook.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook-sa
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
  labels:
    name: {{ .Values.clickhouseOperator.name }}
    {{ include "kubernetes.labels" . | nindent 4 }}
{{- end }}