apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clickhouseOperator.serviceAccountName }}
  labels:
    {{ include "kubernetes.labels" . | nindent 4 }}
    name: {{ .Values.clickhouseOperator.serviceAccountName }}