apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.clickhouseOperator.credentialsToInstances.chCredentialsSecretName }}"
  labels:
    name: "{{ .Values.clickhouseOperator.credentialsToInstances.chCredentialsSecretName }}"
    {{ include "kubernetes.labels" . | nindent 4 }}
data:
  username: {{ .Values.clickhouseOperator.credentialsToInstances.chUsername | b64enc }}
  password: {{ .Values.clickhouseOperator.credentialsToInstances.chPassword | b64enc }}
type: Opaque